name: base
channels:
  - conda-forge
dependencies:
  - python ==3.8.*
  # base image
  - xrootd ==5.4.0
  - conda-build
  - voms
  - jupyterlab
  - ipympl
  - dask_labextension
  - ca-policy-lcg
  - coffea==0.7.20
  - xgboost
  - lz4
  - python-xxhash
  - zstandard
  - pytables
  - python-rapidjson
  - geventhttpclient
  - brotli
  - nomkl
  # docker-coffea-dask
  - python-blosc
  - cytoolz
  - bokeh
  - dask ==2022.9.2
  - distributed ==2022.9.2
  - dask-gateway ==0.9.0
  - dask-jobqueue
  - nomkl
  - scipy ==1.5.3
  - tini
  - jupyter-server-proxy
  - htcondor ==9.2.0
  # coffea[servicex] components available on conda-forge
  - aiostream
  - tenacity
  # Jupyter Lab extensions
  - nodejs
  - jupyterlab-github
  # IRIS-HEP Analysis Systems
  - awkward ==1.10.1
  - uproot ==4.3.7
  - hist ==2.6.2
  - vector ==0.10.0
  - pyhf ==0.7.0
  - iminuit ==2.17.0
  - matplotlib ==3.6.1
  - cabinetry ==0.5.0
  - mplhep ==0.3.26
  - pip >=22.3
