name: base
channels:
  - conda-forge
dependencies:
  - awkward ==1.10.1
  - uproot ==4.3.7
  - hist ==2.6.2
  - vector ==0.10.0
  - pyhf ==0.7.0
  - iminuit ==2.17.0
  - matplotlib ==3.6.1
  - cabinetry ==0.5.0
  - mplhep ==0.3.26
  - pip >=22.3
  - pip:
    - fastjet==3.3.4.0rc9
    - func_adl==3.0
